.TH "get_size.cpp" 3 "Fri Sep 16 2022" "Version 2.28" "Hamlet_reimagined" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_size.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBget_size\fP (const char *filename)"
.br
.RI "Returns size of file in chars\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t get_size (const char * filename)"

.PP
Returns size of file in chars\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP name of file to measure 
.RE
.PP
\fBReturns\fP
.RS 4
sizeof file in chars 
.RE
.PP

.PP
Definition at line 8 of file get_size\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hamlet_reimagined from the source code\&.
