.TH "initializers_and_destructors.cpp" 3 "Fri Sep 16 2022" "Version 2.28" "Hamlet_reimagined" \" -*- nroff -*-
.ad l
.nh
.SH NAME
initializers_and_destructors.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitLine\fP (\fBline\fP *target)"
.br
.RI "Initializes a line type var\&. "
.ti -1c
.RI "void \fBkillLine\fP (\fBline\fP *target)"
.br
.RI "Deinitializes a line type var\&. "
.ti -1c
.RI "void \fBinitText\fP (\fBtext\fP *target)"
.br
.RI "Initializes a text type var\&. "
.ti -1c
.RI "void \fBkillText\fP (\fBtext\fP *target)"
.br
.RI "Deinitializes a text type var\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void initLine (\fBline\fP * target)"

.PP
Initializes a line type var\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP line* to var to init 
.RE
.PP

.PP
Definition at line 8 of file initializers_and_destructors\&.cpp\&.
.SS "void initText (\fBtext\fP * target)"

.PP
Initializes a text type var\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP text* to var to init 
.RE
.PP

.PP
Definition at line 29 of file initializers_and_destructors\&.cpp\&.
.SS "void killLine (\fBline\fP * target)"

.PP
Deinitializes a line type var\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP line* to var to kill 
.RE
.PP

.PP
Definition at line 18 of file initializers_and_destructors\&.cpp\&.
.SS "void killText (\fBtext\fP * target)"

.PP
Deinitializes a text type var\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP text* to var to kill 
.RE
.PP

.PP
Definition at line 41 of file initializers_and_destructors\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hamlet_reimagined from the source code\&.
