.TH "separateLines.cpp" 3 "Sat Sep 17 2022" "Version 2.28" "Hamlet_reimagined" \" -*- nroff -*-
.ad l
.nh
.SH NAME
separateLines.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBseparateLines\fP (\fBtext\fP *writeTo)"
.br
.RI "separates lines in a text "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void separateLines (\fBtext\fP * writeTo)"

.PP
separates lines in a text 
.PP
\fBParameters\fP
.RS 4
\fIwriteTo\fP text* to write to and read from 
.RE
.PP

.PP
Definition at line 5 of file separateLines\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Hamlet_reimagined from the source code\&.
